name: Testing workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  hello-world-from-r:
    name: Hello, world!
    runs-on: ubuntu-latest
    steps:
      - name: Setup R 🔧
        uses: r-lib/actions/setup-r@v2

      - name: Hello world! 💬
        run: cat(paste0("Hello ", Sys.getenv("NAME"), "! 👋"))
        shell: Rscript {0}
        env:
          NAME: "my guy"

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cat(getwd())
          install.packages("remotes")
          remotes::install_local(".", dependencies = TRUE, upgrade = FALSE)
        shell: Rscript {0}

      # - name: Install centroidr package
      #   run: |
      #     install.packages("remotes")
      #     remotes::install_github("olobiolo/centroidr")
      #   shell: Rscript {0}
      - name: Report centroidr installation
        run: |
          any(grepl("centroidr", rownames(installed.packages())))
          grep("cent", rownames(installed.packages()), value = TRUE)
        shell: Rscript {0}
