name: Testing workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  hello-world-from-r:
    name: Hello, world!
    runs-on: ubuntu-latest
    steps:
      - name: Setup R 🔧
        uses: r-lib/actions/setup-r@v2

      - name: Hello world! 💬
        run: cat(paste0("Hello ", Sys.getenv("NAME"), "! 👋"))
        shell: Rscript {0}
        env:
          NAME: "my guy"
      - name: Show token
        run: cat(Sys.getenv("GITHUB_PAT"))
        shell: Rscript {0}
